// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function CENTER(Props) {
  var children = Props.children;
  return React.createElement("div", {
              style: {
                textAlign: "center"
              }
            }, children);
}

var make = CENTER;

export {
  make ,
  
}
/* react Not a pure module */
