// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BASEFONT$React99 from "./BASEFONT.bs.js";

function FONT(Props) {
  var color = Props.color;
  var face = Props.face;
  var size = Props.size;
  var children = Props.children;
  return React.createElement("span", {
              style: BASEFONT$React99.Font.makeStyle(BASEFONT$React99.useContext(/* () */0), color, face, size)
            }, children);
}

var make = FONT;

export {
  make ,
  
}
/* react Not a pure module */
