// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as React99$React99 from "./React99.bs.js";

import "prismjs"
;

import "firacode/distr/fira_code.css"
;

function Index$SuperCoolHeader(Props) {
  return React.createElement(React99$React99.CENTER[/* make */0], {
              children: React.createElement(React99$React99.BLINK[/* make */0], {
                    children: React.createElement(React99$React99.FONT[/* make */0], {
                          color: "red",
                          size: "7",
                          children: "Get up and slam!"
                        })
                  })
            });
}

var SuperCoolHeader = /* module */[/* make */Index$SuperCoolHeader];

function Index$MindBlowingEffect(Props) {
  return React.createElement(React99$React99.BASEFONT[/* make */3], {
              color: "green",
              face: "comic sans ms",
              size: 5,
              children: React.createElement(React99$React99.CENTER[/* make */0], {
                    children: React.createElement("marquee", undefined, "And welcome to the ", React.createElement(React99$React99.FONT[/* make */0], {
                              size: "+1",
                              children: "Jam."
                            }))
                  })
            });
}

var MindBlowingEffect = /* module */[/* make */Index$MindBlowingEffect];

ReactDOMRe.renderToElementWithId(React.createElement(Index$SuperCoolHeader, { }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Index$MindBlowingEffect, { }), "index2");

export {
  SuperCoolHeader ,
  MindBlowingEffect ,
  
}
/*  Not a pure module */
