/* Untyped file generated by genType. */

import * as React99BS from './React99.bs';

export const BLINK_make = React99BS.BLINK[1];

export const CENTER_make = React99BS.CENTER[0];

export const BASEFONT_useContext = React99BS.BASEFONT[1];

export const BASEFONT_make = React99BS.BASEFONT[2];

export const FONT_make = React99BS.FONT[0];
